"""
Cleanup previous MICA CamtrapDP import data from a Supabase instance.

Removes all projects matching the MICA title pattern, their associated
deployments/media/observations, and the placeholder devices created
during import. Safe to run repeatedly.

Usage:
    python scripts/_cleanup_mica.py \
        --supabase-url https://example.supabase.co \
        --service-role-key <key>

Environment variable alternative:
    SUPABASE_URL            — overrides --supabase-url
    SUPABASE_SERVICE_ROLE_KEY — overrides --service-role-key
"""

import argparse
import os
import sys

from supabase import create_client

# Deterministic bluetooth_ids generated by the import for MICA cameras
MICA_BLUETOOTH_IDS = [
    "5c29037d-564d-535f-8886-bebbe07c5be8",
    "a9cfdc6a-5dac-5ab3-ab32-2aa095ac49d5",
    "3ed0a833-0f05-5334-bb58-9d1bd4c98991",
    "73438216-e603-55df-bfa9-1da56ef538fb",
]


def main():
    parser = argparse.ArgumentParser(description="Remove MICA CamtrapDP example data")
    parser.add_argument(
        "--supabase-url",
        default=os.getenv("SUPABASE_URL", "http://localhost:54321"),
    )
    parser.add_argument(
        "--service-role-key",
        default=os.getenv("SUPABASE_SERVICE_ROLE_KEY", ""),
    )
    args = parser.parse_args()

    if not args.service_role_key:
        print("✗  --service-role-key is required (or set SUPABASE_SERVICE_ROLE_KEY)")
        sys.exit(1)

    url = args.supabase_url.rstrip("/") + "/"
    svc = create_client(url, args.service_role_key)

    # 1. Find MICA projects
    projects = svc.table("projects").select("id, name").ilike("name", "%MICA%").execute()
    print(f"Found {len(projects.data)} MICA project(s):")
    for p in projects.data:
        print(f"  {p['id']}: {p['name'][:80]}")

    # 2. Show conflicting devices
    print("\nDevices with MICA bluetooth_ids:")
    for bt in MICA_BLUETOOTH_IDS:
        d = svc.table("devices").select("id, name").eq("bluetooth_id", bt).execute()
        if d.data:
            print(f"  {d.data[0]['id']}: {d.data[0]['name']} (bt: {bt})")

    # 3. Delete in order: observations → media → deployments → user_roles → projects
    for p in projects.data:
        pid = p["id"]
        deps = svc.table("deployments").select("id").eq("project_id", pid).execute()
        dep_ids = [d["id"] for d in deps.data]
        if dep_ids:
            for did in dep_ids:
                svc.table("observations").delete().eq("deployment_id", did).execute()
                svc.table("media").delete().eq("deployment_id", did).execute()
                print(f"  Deleted obs/media for deployment {did}")
            svc.table("deployments").delete().eq("project_id", pid).execute()
            print(f"  Deleted {len(dep_ids)} deployment(s)")

        svc.table("user_roles").delete().eq("scope_id", pid).eq("scope_type", "project").execute()
        svc.table("projects").delete().eq("id", pid).execute()
        print(f"  Deleted project {pid}")

    # 4. Delete orphan devices
    for bt in MICA_BLUETOOTH_IDS:
        d = svc.table("devices").select("id").eq("bluetooth_id", bt).execute()
        if d.data:
            svc.table("devices").delete().eq("id", d.data[0]["id"]).execute()
            print(f"  Deleted device with bt {bt}")

    print("\nCleanup complete!")


if __name__ == "__main__":
    main()
