# Copyright (c) 2026
# SPDX-License-Identifier: GPL-3.0-or-later
"""Build dev-DB seed fixtures (project + device + deployment) from real data.

Two input modes:

  --from-json <export.json> --media-dir <camera_sd_tree>
      Offline. Reads a pasted SQL export (the json_build_object result) and a
      local camera folder. No DB connection — fits the "run SQL in the cloud
      console and paste" workflow when prod/staging isn't reachable from here.

  --project <uuid> | -d <uuid> ...   (+ SUPABASE_URL / SERVICE_ROLE_KEY in env)
      Live. Pulls the deployment(s) + their project/device straight from a
      Supabase project (read-only).

Output (committed, so every dev DB build is identical):
  ww-backend/supabase/seeds/dev/fixtures.generated.sql   ← real-use-case seed
  ww-website/test-fixtures/camera-trap/sdcard/<label>/…  ← drag-into-website imgs

The generated SQL recreates the REAL project/device/deployment with their
production UUIDs, re-homed to the seed General org and owned by the seed admin
(a0000000-…-000001) so the seed test users can browse them. It is cat-ed into
the dev seed by both ww-backend/scripts/seed-local.sh (local) and
.github/workflows/deploy_cloud_projects.yml (cloud).

Because Wildlife Watcher cameras embed the deployment UUID in EXIF
(``Deployment_ID`` / 0xF200), the sdcard images need NO stamping — dragging them
into the website binds them to the seeded deployment automatically, recreating
the real field workflow (end a deployment on the mobile app → drop the SD-card
images into the website → auto match + annotate).

Requires: python-dotenv, supabase (live mode only), httpx/pillow (live download).
"""
from __future__ import annotations

import argparse
import asyncio
import json
import os
import re
import shutil
import sys
from pathlib import Path
from typing import Any, Optional

from dotenv import load_dotenv

# ── Paths ────────────────────────────────────────────────────────────
REPO_ROOT = Path(__file__).resolve().parent.parent          # ww-website/
BACKEND_DIR = REPO_ROOT / "backend"
FIXTURES_DIR = REPO_ROOT / "test-fixtures" / "camera-trap"
SDCARD_DIR = FIXTURES_DIR / "sdcard"                         # ready-to-upload camera trees
DEFAULT_BACKEND_REPO = REPO_ROOT.parent / "ww-backend"      # sibling repo

# ── Seed constants (must match ww-backend/supabase/seeds/dev/data.sql) ─
SEED_ORG_ID = "b0000000-0000-0000-0000-000000000001"        # General org
SEED_ADMIN = "a0000000-0000-0000-0000-000000000001"         # alice@ww.org
# Columns pulled in live mode (subset known to exist in the seed schema).
_DEP_COLS = (
    "id, project_id, device_id, name, location_name, location_description, "
    "latitude, longitude, altitude, accuracy, deployment_status_id, "
    "deployment_start, deployment_end, capture_method_id, "
    "activity_detection_sensitivity_id, timelapse_interval_seconds, "
    "camera_height, start_deployment_comments, end_deployment_comments"
)


# ── Helpers ──────────────────────────────────────────────────────────


def slugify(name: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", (name or "deployment").lower()).strip("-")
    return s or "deployment"


def sql_str(v: Any) -> str:
    """Quote a value for SQL, or NULL. Numbers/bools pass through."""
    if v is None or v == "":
        return "NULL"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


# ── SQL generation ───────────────────────────────────────────────────


def build_fixture_sql(records: list[dict]) -> str:
    """Emit an idempotent DO block creating project/device/deployment per record.

    Each record is ``{"deployment": {...}, "project": {...}, "device": {...}}``.
    Projects are re-homed to the seed General org and owned by the seed admin so
    the handle_new_project trigger (+ explicit grant) makes them visible to seed
    users. Deployment UUIDs are preserved so the camera EXIF binds on upload.
    """
    out = [
        "-- GENERATED by ww-website/scripts/build_seed_fixtures.py — DO NOT EDIT BY HAND.",
        "-- Real production project/device/deployment, re-homed to the seed General org",
        "-- and owned by the seed admin. Idempotent. Cat-ed into the dev seed by",
        "-- seed-local.sh (local) and deploy_cloud_projects.yml (cloud).",
        "-- Upload test-fixtures/camera-trap/sdcard/<label>/ in the website to bind",
        "-- media via EXIF Deployment_ID and exercise the AI pipeline.",
        "",
        "DO $$",
        "BEGIN",
    ]
    for rec in records:
        d = rec["deployment"]
        p = rec.get("project") or {}
        dev = rec.get("device") or {}
        dep_id = d["id"]
        proj_id = p.get("id") or d.get("project_id")
        dev_id = dev.get("id") or d.get("device_id")
        dev_name = dev.get("name") or "Fixture Cam"
        short = str(dev_id).split("-")[0]
        ended_by = sql_str(SEED_ADMIN) if d.get("deployment_end") else "NULL"

        out += [
            f"  -- {p.get('name', 'project')} → {d.get('name')} ({dep_id})",
            "  INSERT INTO projects (id, name, description, organisation_id, created_by, "
            "modified_by, capture_method_id, activity_detection_sensitivity_id) VALUES",
            f"    ({sql_str(proj_id)}, {sql_str(p.get('name') or 'Imported Template')}, "
            f"{sql_str('Template project derived from real data for dev/AI-pipeline testing.')}, "
            f"{sql_str(SEED_ORG_ID)}, {sql_str(SEED_ADMIN)}, {sql_str(SEED_ADMIN)}, "
            f"{sql_str(d.get('capture_method_id') or 1)}, "
            f"{sql_str(d.get('activity_detection_sensitivity_id') or 2)})",
            "  ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, "
            "organisation_id = EXCLUDED.organisation_id, updated_at = now();",
            "",
            "  -- Make the project visible to the seed admin (trigger also grants on insert).",
            f"  IF NOT EXISTS (SELECT 1 FROM user_roles WHERE user_id = {sql_str(SEED_ADMIN)} "
            f"AND scope_type = 'project' AND scope_id = {sql_str(proj_id)} "
            "AND role = 'project_admin' AND deleted_at IS NULL) THEN",
            "    INSERT INTO user_roles (user_id, role, scope_type, scope_id, granted_by, "
            "modified_by, is_active) VALUES",
            f"      ({sql_str(SEED_ADMIN)}, 'project_admin', 'project', {sql_str(proj_id)}, "
            f"{sql_str(SEED_ADMIN)}, {sql_str(SEED_ADMIN)}, true);",
            "  END IF;",
            "",
            "  INSERT INTO devices (id, name, organisation_id, modified_by, bluetooth_id, "
            "device_eui) VALUES",
            f"    ({sql_str(dev_id)}, {sql_str(dev_name)}, {sql_str(SEED_ORG_ID)}, "
            f"{sql_str(SEED_ADMIN)}, {sql_str('BT_FIX_' + short)}, {sql_str('EUI_FIX_' + short)})",
            "  ON CONFLICT (id) DO NOTHING;",
            "",
            "  INSERT INTO deployments (id, project_id, device_id, name, location_name, "
            "location_description, latitude, longitude, altitude, accuracy, "
            "deployment_status_id, deployment_start, deployment_end, setup_by, ended_by, "
            "capture_method_id, activity_detection_sensitivity_id, "
            "timelapse_interval_seconds, camera_height, start_deployment_comments, "
            "end_deployment_comments) VALUES",
            f"    ({sql_str(dep_id)}, {sql_str(proj_id)}, {sql_str(dev_id)}, "
            f"{sql_str(d.get('name'))}, {sql_str(d.get('location_name'))}, "
            f"{sql_str(d.get('location_description'))}, {sql_str(d.get('latitude'))}, "
            f"{sql_str(d.get('longitude'))}, {sql_str(d.get('altitude'))}, "
            f"{sql_str(d.get('accuracy'))}, {sql_str(d.get('deployment_status_id') or 2)}, "
            f"{sql_str(d.get('deployment_start'))}, {sql_str(d.get('deployment_end'))}, "
            f"{sql_str(SEED_ADMIN)}, {ended_by}, {sql_str(d.get('capture_method_id') or 1)}, "
            f"{sql_str(d.get('activity_detection_sensitivity_id') or 2)}, "
            f"{sql_str(d.get('timelapse_interval_seconds'))}, {sql_str(d.get('camera_height'))}, "
            f"{sql_str(d.get('start_deployment_comments'))}, "
            f"{sql_str(d.get('end_deployment_comments'))})",
            "  ON CONFLICT (id) DO UPDATE SET project_id = EXCLUDED.project_id, "
            "device_id = EXCLUDED.device_id, name = EXCLUDED.name, "
            "latitude = EXCLUDED.latitude, longitude = EXCLUDED.longitude, updated_at = now();",
            "",
            f"  RAISE NOTICE '  ✓ template fixture: % (deployment %)', "
            f"{sql_str(d.get('name'))}, {sql_str(dep_id)};",
            "",
        ]
    out += ["END $$;", ""]
    return "\n".join(out)


def write_sql(records: list[dict], backend_repo: Path) -> Path:
    out = backend_repo / "supabase" / "seeds" / "dev" / "fixtures.generated.sql"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build_fixture_sql(records), encoding="utf-8")
    return out


# ── Media (copy or download) ─────────────────────────────────────────


def copy_sdcard(media_dir: Path, label: str) -> int:
    """Copy a camera SD-card tree into the committed fixtures, preserving layout."""
    dest = SDCARD_DIR / label
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(media_dir, dest)
    return sum(1 for p in dest.rglob("*") if p.suffix.lower() in (".jpg", ".jpeg"))


# ── Live mode (optional) ─────────────────────────────────────────────


def live_records(args) -> list[dict]:
    from supabase import create_client
    url = os.environ.get("SUPABASE_URL")
    key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY")
    if not url or not key:
        sys.exit("❌ Live mode needs SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY (point at the source DB).")
    print(f"🔌 Source Supabase: {url}")
    client = create_client(url, key)

    dep_rows: list[dict] = []
    if args.deployment:
        for did in args.deployment:
            r = client.table("deployments").select(_DEP_COLS + ", project_id, device_id").eq("id", did).limit(1).execute()
            if r.data:
                dep_rows.append(r.data[0])
    else:
        q = client.table("deployments").select(_DEP_COLS + ", project_id, device_id").is_("deleted_at", "null")
        if args.project:
            q = q.eq("project_id", args.project)
        dep_rows = (q.order("deployment_start", desc=True).limit(args.limit_deployments).execute().data or [])

    records = []
    for d in dep_rows:
        proj = client.table("projects").select("id, name, organisation_id").eq("id", d.get("project_id")).limit(1).execute().data
        dev = client.table("devices").select("id, name").eq("id", d.get("device_id")).limit(1).execute().data
        records.append({"deployment": d, "project": (proj or [{}])[0], "device": (dev or [{}])[0]})
    return records


# ── Main ─────────────────────────────────────────────────────────────


def main() -> None:
    try:  # Windows consoles default to cp1252; emit UTF-8 so status lines don't crash.
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass
    load_dotenv(REPO_ROOT / ".env")
    ap = argparse.ArgumentParser(description="Build dev seed fixtures from real deployments.")
    ap.add_argument("--from-json", type=Path, help="Pasted SQL export (json_build_object result).")
    ap.add_argument("--media-dir", type=Path, help="Local camera SD-card tree to copy (with --from-json).")
    ap.add_argument("-d", "--deployment", action="append", help="Live: deployment UUID (repeatable).")
    ap.add_argument("-p", "--project", help="Live: project UUID — pull its deployments.")
    ap.add_argument("--limit-deployments", type=int, default=3)
    ap.add_argument("--backend-repo", type=Path, default=DEFAULT_BACKEND_REPO)
    args = ap.parse_args()

    # Build the record list (deployment + project + device per entry).
    if args.from_json:
        raw = json.loads(args.from_json.read_text(encoding="utf-8"))
        items = raw if isinstance(raw, list) else [raw]
        records = [{"deployment": it["deployment"], "project": it.get("project"), "device": it.get("device")} for it in items]
    elif args.deployment or args.project:
        records = live_records(args)
    else:
        ap.error("Provide --from-json (+ --media-dir) or --deployment/--project.")

    if not records:
        sys.exit("❌ No deployments resolved.")

    # Media: copy the SD-card tree (from-json) — camera EXIF already binds, no stamping.
    if args.media_dir:
        label = slugify((records[0]["project"] or {}).get("name") or records[0]["deployment"].get("name"))
        n = copy_sdcard(args.media_dir, label)
        print(f"📷 copied {n} image(s) → {(SDCARD_DIR / label).relative_to(REPO_ROOT)}/ (pre-bound via EXIF)")

    sql_path = write_sql(records, args.backend_repo)
    print(f"📝 wrote {sql_path}")
    for rec in records:
        d = rec["deployment"]
        print(f"   • {(rec['project'] or {}).get('name')} → {d.get('name')}  [{d['id']}]")

    print("\n✅ Done. Next:")
    print("   • Commit ww-backend/supabase/seeds/dev/fixtures.generated.sql + test-fixtures/camera-trap/sdcard/")
    print("   • Cloud: run .github/workflows/deploy_cloud_projects.yml (dev) — it cat's the fixture into the seed.")
    print("   • Local: supabase db reset && bash scripts/seed-local.sh")
    print("   • Then drag sdcard/<label>/ into the website (login as alice@ww.org) → EXIF binds → AI pipeline runs.")


if __name__ == "__main__":
    main()
